### ISSUE TITLE
Форма для Юридических лиц

### ISSUE THREAD

**Issue by beibus** [Entea/transit-permit#3]
Форма для Юридических лиц должна содержать следующие поля:

1. **Наименование компании** (*обязательное поле)
2. **ФИО Руководителя** (*обязательное поле)
3. **Секция с возможностью добавлять несколько строк с такими полями как** - Марка и модель транспортного средства, госномер а/м. (*обязательна минимум одна заполненая строка)
4. **список ФИО сотрудников**
5.  **контактный номер руководителя/компании.**
6. **Район планируемых перемещений** (*обязательное поле)
7. **Поле email** - для того чтобы получить одобренный документ с QR кодом. (*обязательное поле)

Нужна возможность распечатать заполненный бланк, для оффлайна подачи, возможность распечатать пустую форму для ручного заполнения.

Нужна возможность скачать следующий документ - Справка от компании для сотрудника: https://drive.google.com/file/d/1iPxb1DIecbED_ZAaY2ZSTyPU-bVN4P01/view?usp=sharing

**Comment by Entea** [comment]
@beibus видимо в форму нужно также добавить:
* список сотрудников
* контактный номер руководителя/компании.

**Comment by beibus** [comment]
@ipatiev 
1. скройте пожалуйста поле ФИО Сотрудника?
2. Кнопку - Добавить Сотрудника переименуйте в "Добавить ТС"
3. Весь блок переименуйте в "Транспортные средства"
